#!/bin/bash

# Choose the run mode
# 1) Relay == 1
# 2) Block Producer == 2

export CARDANO_RUN_MODE=1


# Relay Mode

export CARDANO_PORT=3001
export CARDANO_CONFIG_PATH=/home/cardano/cnode/files/mainnet/mainnet-config.json
export CARDANO_TOPOLOGY_PATH=/home/cardano/cnode/files/mainnet/mainnet-topology.json
export CARDANO_DB_PATH=/home/cardano/cnode/db
export CARDANO_NODE_SOCKET_PATH=/home/cardano/cnode/node.socket
export CARDANO_HOST_ADDRESS=0.0.0.0


# Block Producer Mode

# Store the hot keys within ~/cnode/bp-keys
# You may adjust the names for the hot key but having the extensions *.kes.skey, *.vrf.skey and *.opcert should suffice
# Uncomment the 3 entries below to ensure once the hot keys are placed

export CARDANO_KES_KEY_PATH=/home/cardano/cnode/bp-keys/*.*kes*.skey
export CARDANO_VRF_KEY_PATH=/home/cardano/cnode/bp-keys/*.*vrf*.skey
export CARDANO_OP_CERT_PATH=/home/cardano/cnode/bp-keys/*.opcert


# Some SPOs may want to restart their cardano-node service at fixed intervals.

# If you wish to do so, set the RUNTIME value in seconds.
# This will issue a restart service command after the specified time.
# Set to 0 to disable the restart service feature.

#export RUNTIME=0

# Restart time presets

#export RUNTIME=14400 # 4 hour intervals
export RUNTIME=28800 # 8 hour intervals
#export RUNTIME=43200 # 12 hour intervals


# For Prometheus Use

export PROMETHEUS_LISTEN_ADDRESS=localhost:9090
export NODE_EXPORTER_LISTEN_ADDRESS=localhost:8100
